services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: puntodeventa
      POSTGRES_PASSWORD: puntodeventa1234
      POSTGRES_DB: puntodeventa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://puntodeventa:puntodeventa1234@db:5432/puntodeventa
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
  app:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_data: